# Generated by Django 6.0 on 2025-12-21 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0006_profile_home_address_profile_is_verified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "base_fare",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
                ),
                (
                    "per_km_rate",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
                ),
                (
                    "per_minute_rate",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=10),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="vehicle_types/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("year", models.PositiveIntegerField()),
                ("plate_number", models.CharField(max_length=20, unique=True)),
                ("color", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "registration_document",
                    models.FileField(blank=True, null=True, upload_to="vehicle_docs/"),
                ),
                (
                    "insurance_document",
                    models.FileField(blank=True, null=True, upload_to="vehicle_docs/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="users.profile",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="vehicles.vehicletype",
                    ),
                ),
            ],
        ),
    ]
