# Generated by Django 6.0 on 2025-12-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_wallet_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="provider",
            field=models.CharField(default="DEMO", max_length=50),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
