# Generated by Django 6.0 on 2025-12-20 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("pickup_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("drop_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("drop_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=6)),
                ("estimated_fare", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("ASSIGNED", "Assigned"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("PAID", "Paid"),
                        ],
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rides_as_driver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rides_as_rider",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
