# Generated by Django 6.0 on 2025-12-20 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="rejected_drivers",
            field=models.ManyToManyField(
                blank=True, related_name="rejected_rides", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
