# Generated by Django 6.0 on 2025-12-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0003_ride_available_seats_ride_is_scheduled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="drop_lat",
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name="ride",
            name="drop_lng",
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_lat",
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_lng",
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
