# Generated by Django 6.0 on 2025-12-20 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0004_alter_ride_drop_lat_alter_ride_drop_lng_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="rider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_as_rider",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
