# Generated by Django 6.0 on 2025-12-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0005_alter_ride_rider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="drop_lat",
            field=models.DecimalField(decimal_places=16, max_digits=22),
        ),
        migrations.AlterField(
            model_name="ride",
            name="drop_lng",
            field=models.DecimalField(decimal_places=16, max_digits=22),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_lat",
            field=models.DecimalField(decimal_places=16, max_digits=22),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_lng",
            field=models.DecimalField(decimal_places=16, max_digits=22),
        ),
    ]
