# Generated by Django 6.0 on 2025-12-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0008_ride_actual_vehicle_ride_cancellation_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="negotiation_status",
            field=models.CharField(
                choices=[
                    ("NONE", "No Negotiation"),
                    ("PENDING", "Pending Driver Response"),
                    ("ACCEPTED", "Driver Accepted"),
                    ("REJECTED", "Driver Rejected"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="proposed_fare",
            field=models.IntegerField(
                blank=True, help_text="Passenger's proposed fare in BDT", null=True
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("ASSIGNED", "Assigned"),
                    ("ONGOING", "Ongoing"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("PAID", "Paid"),
                    ("FINISHED", "Finished"),
                ],
                default="REQUESTED",
                max_length=20,
            ),
        ),
    ]
