# Generated by Django 6.0 on 2025-12-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_current_lat_profile_current_lng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="current_lat",
            field=models.DecimalField(
                blank=True, decimal_places=16, max_digits=22, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="current_lng",
            field=models.DecimalField(
                blank=True, decimal_places=16, max_digits=22, null=True
            ),
        ),
    ]
