# Generated by Django 6.0 on 2025-12-21 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_profile_car_color_profile_car_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="home_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="work_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DriverDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("NID", "National ID"),
                            ("LICENSE", "Driving License"),
                            ("TIN", "Tax Certificate"),
                            ("UTILITY", "Utility Bill (Address Proof)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("document_number", models.CharField(max_length=50)),
                (
                    "file_path",
                    models.FileField(blank=True, null=True, upload_to="driver_docs/"),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="users.profile",
                    ),
                ),
            ],
        ),
    ]
